apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notebook-gallery.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notebook-gallery.labels" . | nindent 4 }}
data:
  config.json: |
    {{- $defaultBuildkit := printf "%s-buildkit-service" .Release.Name }}
    {{- $build := merge .Values.build (dict "buildkitServiceName" $defaultBuildkit) }}
    {{- dict
          "notebooks"        .Values.notebooks
          "sessionDefaults"  .Values.sessionDefaults
          "theme"            .Values.theme
          "ingress"          .Values.ingress
          "image"            .Values.image
          "build"            $build
          "namespace"        .Release.Namespace
          "cacheDir"         .Values.cacheDir
      | toJson | nindent 4 }}
