apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notebook-gallery.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notebook-gallery.labels" . | nindent 4 }}
automountServiceAccountToken: true
